# Generated by Django 4.2.1 on 2023-05-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='populationData',
            fields=[
                ('population_id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('Dist', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-year',),
            },
        ),
    ]
