# Generated by Django 4.2.1 on 2023-05-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_citydata_rename_dist_populationdata_dist'),
    ]

    operations = [
        migrations.CreateModel(
            name='crimeData',
            fields=[
                ('crime_id', models.IntegerField(primary_key=True, serialize=False)),
                ('crime', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('crime_id',),
            },
        ),
    ]
