# Generated by Django 4.2.1 on 2023-05-29 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_alter_populationdata_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='crimeData',
            new_name='categoryData',
        ),
        migrations.AlterModelOptions(
            name='categorydata',
            options={'ordering': ('category_id',)},
        ),
        migrations.RenameField(
            model_name='categorydata',
            old_name='crime',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='categorydata',
            old_name='crime_id',
            new_name='category_id',
        ),
    ]
