# Generated by Django 4.2.1 on 2023-05-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_rename_month_crimedata_cleard'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimedata',
            name='month',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
