# Generated by Django 4.2.1 on 2023-06-07 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_alter_citydata_options_remove_citydata_city_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorydata',
            options={'ordering': ('category',)},
        ),
        migrations.RemoveField(
            model_name='categorydata',
            name='category_id',
        ),
        migrations.AlterField(
            model_name='categorydata',
            name='category',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.citydata'),
        ),
    ]
