# Generated by Django 4.2.1 on 2023-05-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_populationdata_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populationdata',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
