# Generated by Django 4.2.1 on 2023-05-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_crimedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimedata',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='populationdata',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
