# Generated by Django 4.2.1 on 2023-05-29 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_alter_crimedata_category_alter_crimedata_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crimedata',
            old_name='month',
            new_name='cleard',
        ),
    ]
