# Generated by Django 4.2.1 on 2023-06-07 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citydata',
            options={'ordering': ('city',)},
        ),
        migrations.RemoveField(
            model_name='citydata',
            name='city_id',
        ),
        migrations.AlterField(
            model_name='citydata',
            name='city',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='populationdata',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.citydata'),
        ),
    ]
