# Generated by Django 4.2.1 on 2023-06-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_alter_categorydata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimedata',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
