# Generated by Django 4.2.1 on 2023-06-07 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_alter_crimedata_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimedata',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.categorydata'),
        ),
    ]
